internal class EventHubSupportedData
{
    public static readonly IReadOnlyDictionary<string, string> SkuToSkuNameMap = new Dictionary<string, string>()
    {
        {
            "Basic",
                "Basic"
        },
        {
            "Standard",
                "Standard"
        },
        {
            "Premium",
                "Premium"
        },
        {
            "Dedicated",
                "Dedicated"
        },
        {
            "Capture",
                "Capture"
        },
        {
            "Empty",
                ""
        }
    };
}
