name: Test GitHub action

on: [workflow_dispatch]

jobs:
  test_github_action:
    runs-on: ubuntu-latest
    name: A job to test GitHub Action
    steps:
      - name: Run action
        id: run
        uses: TheCloudTheory/azure-cost-estimator-action@main
        with:
          template-file: 'path'
          resource-group-name: 'rg'
