name: Test GitHub action

on: [workflow_dispatch]

jobs:
  test_github_action:
    runs-on: ubuntu-latest
    name: A job to test GitHub Action
    steps:
      - uses: actions/checkout@v3
      - name: Azure Login
        uses: Azure/login@v1.4.6
        with:
          creds: ${{ secrets.SP_CREDS }}
      - name: Run action
        id: run
        uses: TheCloudTheory/azure-cost-estimator-action@0.0.6-preview
        with:
          template-file: 'ace-tests/templates/acr.json'
          subscription-id: 'cf70b558-b930-45e4-9048-ebcefb926adf'
          resource-group-name: 'arm-estimator-tests-rg'
